// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/chat-web.proto

package chatweb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ChatWeb service

func NewChatWebEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ChatWeb service

type ChatWebService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (ChatWeb_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (ChatWeb_PingPongService, error)
}

type chatWebService struct {
	c    client.Client
	name string
}

func NewChatWebService(name string, c client.Client) ChatWebService {
	return &chatWebService{
		c:    c,
		name: name,
	}
}

func (c *chatWebService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ChatWeb.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatWebService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (ChatWeb_StreamService, error) {
	req := c.c.NewRequest(c.name, "ChatWeb.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &chatWebServiceStream{stream}, nil
}

type ChatWeb_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type chatWebServiceStream struct {
	stream client.Stream
}

func (x *chatWebServiceStream) Close() error {
	return x.stream.Close()
}

func (x *chatWebServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *chatWebServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *chatWebServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *chatWebServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatWebService) PingPong(ctx context.Context, opts ...client.CallOption) (ChatWeb_PingPongService, error) {
	req := c.c.NewRequest(c.name, "ChatWeb.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &chatWebServicePingPong{stream}, nil
}

type ChatWeb_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type chatWebServicePingPong struct {
	stream client.Stream
}

func (x *chatWebServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *chatWebServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *chatWebServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *chatWebServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *chatWebServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *chatWebServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ChatWeb service

type ChatWebHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, ChatWeb_StreamStream) error
	PingPong(context.Context, ChatWeb_PingPongStream) error
}

func RegisterChatWebHandler(s server.Server, hdlr ChatWebHandler, opts ...server.HandlerOption) error {
	type chatWeb interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type ChatWeb struct {
		chatWeb
	}
	h := &chatWebHandler{hdlr}
	return s.Handle(s.NewHandler(&ChatWeb{h}, opts...))
}

type chatWebHandler struct {
	ChatWebHandler
}

func (h *chatWebHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ChatWebHandler.Call(ctx, in, out)
}

func (h *chatWebHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ChatWebHandler.Stream(ctx, m, &chatWebStreamStream{stream})
}

type ChatWeb_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type chatWebStreamStream struct {
	stream server.Stream
}

func (x *chatWebStreamStream) Close() error {
	return x.stream.Close()
}

func (x *chatWebStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *chatWebStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *chatWebStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *chatWebStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *chatWebHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ChatWebHandler.PingPong(ctx, &chatWebPingPongStream{stream})
}

type ChatWeb_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type chatWebPingPongStream struct {
	stream server.Stream
}

func (x *chatWebPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *chatWebPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *chatWebPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *chatWebPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *chatWebPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *chatWebPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
