// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user-srv.proto

package usersrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserSrv service

func NewUserSrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserSrv service

type UserSrvService interface {
	InspectUser(ctx context.Context, in *InspectRequest, opts ...client.CallOption) (*InspectResponse, error)
	UpdateUser(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	AddUser(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error)
	DeleteUser(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
}

type userSrvService struct {
	c    client.Client
	name string
}

func NewUserSrvService(name string, c client.Client) UserSrvService {
	return &userSrvService{
		c:    c,
		name: name,
	}
}

func (c *userSrvService) InspectUser(ctx context.Context, in *InspectRequest, opts ...client.CallOption) (*InspectResponse, error) {
	req := c.c.NewRequest(c.name, "UserSrv.InspectUser", in)
	out := new(InspectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvService) UpdateUser(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.name, "UserSrv.UpdateUser", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvService) AddUser(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error) {
	req := c.c.NewRequest(c.name, "UserSrv.AddUser", in)
	out := new(AddResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvService) DeleteUser(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.name, "UserSrv.DeleteUser", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserSrv service

type UserSrvHandler interface {
	InspectUser(context.Context, *InspectRequest, *InspectResponse) error
	UpdateUser(context.Context, *UpdateRequest, *UpdateResponse) error
	AddUser(context.Context, *AddRequest, *AddResponse) error
	DeleteUser(context.Context, *DeleteRequest, *DeleteResponse) error
}

func RegisterUserSrvHandler(s server.Server, hdlr UserSrvHandler, opts ...server.HandlerOption) error {
	type userSrv interface {
		InspectUser(ctx context.Context, in *InspectRequest, out *InspectResponse) error
		UpdateUser(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error
		AddUser(ctx context.Context, in *AddRequest, out *AddResponse) error
		DeleteUser(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error
	}
	type UserSrv struct {
		userSrv
	}
	h := &userSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&UserSrv{h}, opts...))
}

type userSrvHandler struct {
	UserSrvHandler
}

func (h *userSrvHandler) InspectUser(ctx context.Context, in *InspectRequest, out *InspectResponse) error {
	return h.UserSrvHandler.InspectUser(ctx, in, out)
}

func (h *userSrvHandler) UpdateUser(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.UserSrvHandler.UpdateUser(ctx, in, out)
}

func (h *userSrvHandler) AddUser(ctx context.Context, in *AddRequest, out *AddResponse) error {
	return h.UserSrvHandler.AddUser(ctx, in, out)
}

func (h *userSrvHandler) DeleteUser(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.UserSrvHandler.DeleteUser(ctx, in, out)
}
