// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/class-srv.proto

package classsrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ClassSrv service

func NewClassSrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ClassSrv service

type ClassSrvService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (ClassSrv_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (ClassSrv_PingPongService, error)
}

type classSrvService struct {
	c    client.Client
	name string
}

func NewClassSrvService(name string, c client.Client) ClassSrvService {
	return &classSrvService{
		c:    c,
		name: name,
	}
}

func (c *classSrvService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ClassSrv.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classSrvService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (ClassSrv_StreamService, error) {
	req := c.c.NewRequest(c.name, "ClassSrv.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &classSrvServiceStream{stream}, nil
}

type ClassSrv_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type classSrvServiceStream struct {
	stream client.Stream
}

func (x *classSrvServiceStream) Close() error {
	return x.stream.Close()
}

func (x *classSrvServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *classSrvServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *classSrvServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *classSrvServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *classSrvService) PingPong(ctx context.Context, opts ...client.CallOption) (ClassSrv_PingPongService, error) {
	req := c.c.NewRequest(c.name, "ClassSrv.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &classSrvServicePingPong{stream}, nil
}

type ClassSrv_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type classSrvServicePingPong struct {
	stream client.Stream
}

func (x *classSrvServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *classSrvServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *classSrvServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *classSrvServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *classSrvServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *classSrvServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ClassSrv service

type ClassSrvHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, ClassSrv_StreamStream) error
	PingPong(context.Context, ClassSrv_PingPongStream) error
}

func RegisterClassSrvHandler(s server.Server, hdlr ClassSrvHandler, opts ...server.HandlerOption) error {
	type classSrv interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type ClassSrv struct {
		classSrv
	}
	h := &classSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&ClassSrv{h}, opts...))
}

type classSrvHandler struct {
	ClassSrvHandler
}

func (h *classSrvHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ClassSrvHandler.Call(ctx, in, out)
}

func (h *classSrvHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ClassSrvHandler.Stream(ctx, m, &classSrvStreamStream{stream})
}

type ClassSrv_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type classSrvStreamStream struct {
	stream server.Stream
}

func (x *classSrvStreamStream) Close() error {
	return x.stream.Close()
}

func (x *classSrvStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *classSrvStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *classSrvStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *classSrvStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *classSrvHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ClassSrvHandler.PingPong(ctx, &classSrvPingPongStream{stream})
}

type ClassSrv_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type classSrvPingPongStream struct {
	stream server.Stream
}

func (x *classSrvPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *classSrvPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *classSrvPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *classSrvPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *classSrvPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *classSrvPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
