// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/teacher-srv.proto

package teachersrv

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Teacher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeacherID   string   `protobuf:"bytes,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pic         string   `protobuf:"bytes,3,opt,name=pic,proto3" json:"pic,omitempty"`
	Tag         []string `protobuf:"bytes,4,rep,name=tag,proto3" json:"tag,omitempty"`
	Tel         string   `protobuf:"bytes,5,opt,name=tel,proto3" json:"tel,omitempty"`
	Description string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Teacher) Reset() {
	*x = Teacher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Teacher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teacher) ProtoMessage() {}

func (x *Teacher) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teacher.ProtoReflect.Descriptor instead.
func (*Teacher) Descriptor() ([]byte, []int) {
	return file_proto_teacher_srv_proto_rawDescGZIP(), []int{0}
}

func (x *Teacher) GetTeacherID() string {
	if x != nil {
		return x.TeacherID
	}
	return ""
}

func (x *Teacher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Teacher) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *Teacher) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Teacher) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *Teacher) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetTeachersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeacherID string `protobuf:"bytes,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	AgencyID  string `protobuf:"bytes,2,opt,name=agencyID,proto3" json:"agencyID,omitempty"`
}

func (x *GetTeachersRequest) Reset() {
	*x = GetTeachersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_srv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeachersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeachersRequest) ProtoMessage() {}

func (x *GetTeachersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_srv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeachersRequest.ProtoReflect.Descriptor instead.
func (*GetTeachersRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_srv_proto_rawDescGZIP(), []int{1}
}

func (x *GetTeachersRequest) GetTeacherID() string {
	if x != nil {
		return x.TeacherID
	}
	return ""
}

func (x *GetTeachersRequest) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

type GetTeachersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teachers []*Teacher `protobuf:"bytes,1,rep,name=teachers,proto3" json:"teachers,omitempty"`
	Msg      string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Status   int32      `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetTeachersResponse) Reset() {
	*x = GetTeachersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_srv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeachersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeachersResponse) ProtoMessage() {}

func (x *GetTeachersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_srv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeachersResponse.ProtoReflect.Descriptor instead.
func (*GetTeachersResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_srv_proto_rawDescGZIP(), []int{2}
}

func (x *GetTeachersResponse) GetTeachers() []*Teacher {
	if x != nil {
		return x.Teachers
	}
	return nil
}

func (x *GetTeachersResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetTeachersResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddTeacherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgencyID string   `protobuf:"bytes,1,opt,name=agencyID,proto3" json:"agencyID,omitempty"`
	Teacher  *Teacher `protobuf:"bytes,2,opt,name=teacher,proto3" json:"teacher,omitempty"`
}

func (x *AddTeacherRequest) Reset() {
	*x = AddTeacherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_srv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeacherRequest) ProtoMessage() {}

func (x *AddTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_srv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeacherRequest.ProtoReflect.Descriptor instead.
func (*AddTeacherRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_srv_proto_rawDescGZIP(), []int{3}
}

func (x *AddTeacherRequest) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

func (x *AddTeacherRequest) GetTeacher() *Teacher {
	if x != nil {
		return x.Teacher
	}
	return nil
}

type AddTeacherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeacherID string `protobuf:"bytes,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	Msg       string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Status    int32  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddTeacherResponse) Reset() {
	*x = AddTeacherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_srv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeacherResponse) ProtoMessage() {}

func (x *AddTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_srv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeacherResponse.ProtoReflect.Descriptor instead.
func (*AddTeacherResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_srv_proto_rawDescGZIP(), []int{4}
}

func (x *AddTeacherResponse) GetTeacherID() string {
	if x != nil {
		return x.TeacherID
	}
	return ""
}

func (x *AddTeacherResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AddTeacherResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateTeacherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teacher  *Teacher `protobuf:"bytes,1,opt,name=teacher,proto3" json:"teacher,omitempty"`
	AgencyID string   `protobuf:"bytes,2,opt,name=agencyID,proto3" json:"agencyID,omitempty"`
}

func (x *UpdateTeacherRequest) Reset() {
	*x = UpdateTeacherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_srv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeacherRequest) ProtoMessage() {}

func (x *UpdateTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_srv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeacherRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeacherRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_srv_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTeacherRequest) GetTeacher() *Teacher {
	if x != nil {
		return x.Teacher
	}
	return nil
}

func (x *UpdateTeacherRequest) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

type UpdateTeacherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg    string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Status int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateTeacherResponse) Reset() {
	*x = UpdateTeacherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_srv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeacherResponse) ProtoMessage() {}

func (x *UpdateTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_srv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeacherResponse.ProtoReflect.Descriptor instead.
func (*UpdateTeacherResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_srv_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTeacherResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UpdateTeacherResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeleteTeacherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeacherID string `protobuf:"bytes,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	AgencyID  string `protobuf:"bytes,2,opt,name=agencyID,proto3" json:"agencyID,omitempty"`
}

func (x *DeleteTeacherRequest) Reset() {
	*x = DeleteTeacherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_srv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherRequest) ProtoMessage() {}

func (x *DeleteTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_srv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeacherRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_srv_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTeacherRequest) GetTeacherID() string {
	if x != nil {
		return x.TeacherID
	}
	return ""
}

func (x *DeleteTeacherRequest) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

type DeleteTeacherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg    string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Status int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteTeacherResponse) Reset() {
	*x = DeleteTeacherResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_teacher_srv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherResponse) ProtoMessage() {}

func (x *DeleteTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_srv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeacherResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_srv_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTeacherResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DeleteTeacherResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_teacher_srv_proto protoreflect.FileDescriptor

var file_proto_teacher_srv_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x2d,
	0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x73, 0x72, 0x76, 0x22, 0x93, 0x01, 0x0a, 0x07, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x22, 0x70, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x72,
	0x76, 0x2e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x08, 0x74, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5e, 0x0a,
	0x11, 0x41, 0x64, 0x64, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x12, 0x2d,
	0x0a, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x72, 0x76, 0x2e, 0x54, 0x65, 0x61,
	0x63, 0x68, 0x65, 0x72, 0x52, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x22, 0x5c, 0x0a,
	0x12, 0x41, 0x64, 0x64, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x61, 0x0a, 0x14, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x72,
	0x76, 0x2e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x22, 0x41,
	0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x50, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x61,
	0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65,
	0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x49, 0x44, 0x22, 0x41, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61,
	0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xdd, 0x02, 0x0a, 0x0a, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x53, 0x72, 0x76, 0x12, 0x50, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63,
	0x68, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x2e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x72,
	0x76, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x72,
	0x76, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x54, 0x65,
	0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73,
	0x72, 0x76, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x72,
	0x76, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65,
	0x72, 0x73, 0x72, 0x76, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x74, 0x65, 0x61, 0x63,
	0x68, 0x65, 0x72, 0x73, 0x72, 0x76, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61,
	0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56,
	0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12,
	0x20, 0x2e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x72, 0x76, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x72, 0x76, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x72, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_teacher_srv_proto_rawDescOnce sync.Once
	file_proto_teacher_srv_proto_rawDescData = file_proto_teacher_srv_proto_rawDesc
)

func file_proto_teacher_srv_proto_rawDescGZIP() []byte {
	file_proto_teacher_srv_proto_rawDescOnce.Do(func() {
		file_proto_teacher_srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_teacher_srv_proto_rawDescData)
	})
	return file_proto_teacher_srv_proto_rawDescData
}

var file_proto_teacher_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_teacher_srv_proto_goTypes = []interface{}{
	(*Teacher)(nil),               // 0: teachersrv.Teacher
	(*GetTeachersRequest)(nil),    // 1: teachersrv.GetTeachersRequest
	(*GetTeachersResponse)(nil),   // 2: teachersrv.GetTeachersResponse
	(*AddTeacherRequest)(nil),     // 3: teachersrv.AddTeacherRequest
	(*AddTeacherResponse)(nil),    // 4: teachersrv.AddTeacherResponse
	(*UpdateTeacherRequest)(nil),  // 5: teachersrv.UpdateTeacherRequest
	(*UpdateTeacherResponse)(nil), // 6: teachersrv.UpdateTeacherResponse
	(*DeleteTeacherRequest)(nil),  // 7: teachersrv.DeleteTeacherRequest
	(*DeleteTeacherResponse)(nil), // 8: teachersrv.DeleteTeacherResponse
}
var file_proto_teacher_srv_proto_depIdxs = []int32{
	0, // 0: teachersrv.GetTeachersResponse.teachers:type_name -> teachersrv.Teacher
	0, // 1: teachersrv.AddTeacherRequest.teacher:type_name -> teachersrv.Teacher
	0, // 2: teachersrv.UpdateTeacherRequest.teacher:type_name -> teachersrv.Teacher
	1, // 3: teachersrv.TeacherSrv.GetTeachers:input_type -> teachersrv.GetTeachersRequest
	3, // 4: teachersrv.TeacherSrv.AddTeacher:input_type -> teachersrv.AddTeacherRequest
	5, // 5: teachersrv.TeacherSrv.UpdateTeacher:input_type -> teachersrv.UpdateTeacherRequest
	7, // 6: teachersrv.TeacherSrv.DeleteTeacher:input_type -> teachersrv.DeleteTeacherRequest
	2, // 7: teachersrv.TeacherSrv.GetTeachers:output_type -> teachersrv.GetTeachersResponse
	4, // 8: teachersrv.TeacherSrv.AddTeacher:output_type -> teachersrv.AddTeacherResponse
	6, // 9: teachersrv.TeacherSrv.UpdateTeacher:output_type -> teachersrv.UpdateTeacherResponse
	8, // 10: teachersrv.TeacherSrv.DeleteTeacher:output_type -> teachersrv.DeleteTeacherResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_teacher_srv_proto_init() }
func file_proto_teacher_srv_proto_init() {
	if File_proto_teacher_srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_teacher_srv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Teacher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_srv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeachersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_srv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeachersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_srv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTeacherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_srv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTeacherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_srv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTeacherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_srv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTeacherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_srv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTeacherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_teacher_srv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTeacherResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_teacher_srv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_teacher_srv_proto_goTypes,
		DependencyIndexes: file_proto_teacher_srv_proto_depIdxs,
		MessageInfos:      file_proto_teacher_srv_proto_msgTypes,
	}.Build()
	File_proto_teacher_srv_proto = out.File
	file_proto_teacher_srv_proto_rawDesc = nil
	file_proto_teacher_srv_proto_goTypes = nil
	file_proto_teacher_srv_proto_depIdxs = nil
}
