// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/teacher-srv.proto

package teachersrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TeacherSrv service

func NewTeacherSrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TeacherSrv service

type TeacherSrvService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (TeacherSrv_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (TeacherSrv_PingPongService, error)
}

type teacherSrvService struct {
	c    client.Client
	name string
}

func NewTeacherSrvService(name string, c client.Client) TeacherSrvService {
	return &teacherSrvService{
		c:    c,
		name: name,
	}
}

func (c *teacherSrvService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TeacherSrv.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherSrvService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (TeacherSrv_StreamService, error) {
	req := c.c.NewRequest(c.name, "TeacherSrv.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &teacherSrvServiceStream{stream}, nil
}

type TeacherSrv_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type teacherSrvServiceStream struct {
	stream client.Stream
}

func (x *teacherSrvServiceStream) Close() error {
	return x.stream.Close()
}

func (x *teacherSrvServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *teacherSrvServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *teacherSrvServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *teacherSrvServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *teacherSrvService) PingPong(ctx context.Context, opts ...client.CallOption) (TeacherSrv_PingPongService, error) {
	req := c.c.NewRequest(c.name, "TeacherSrv.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &teacherSrvServicePingPong{stream}, nil
}

type TeacherSrv_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type teacherSrvServicePingPong struct {
	stream client.Stream
}

func (x *teacherSrvServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *teacherSrvServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *teacherSrvServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *teacherSrvServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *teacherSrvServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *teacherSrvServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TeacherSrv service

type TeacherSrvHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, TeacherSrv_StreamStream) error
	PingPong(context.Context, TeacherSrv_PingPongStream) error
}

func RegisterTeacherSrvHandler(s server.Server, hdlr TeacherSrvHandler, opts ...server.HandlerOption) error {
	type teacherSrv interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type TeacherSrv struct {
		teacherSrv
	}
	h := &teacherSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&TeacherSrv{h}, opts...))
}

type teacherSrvHandler struct {
	TeacherSrvHandler
}

func (h *teacherSrvHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.TeacherSrvHandler.Call(ctx, in, out)
}

func (h *teacherSrvHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.TeacherSrvHandler.Stream(ctx, m, &teacherSrvStreamStream{stream})
}

type TeacherSrv_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type teacherSrvStreamStream struct {
	stream server.Stream
}

func (x *teacherSrvStreamStream) Close() error {
	return x.stream.Close()
}

func (x *teacherSrvStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *teacherSrvStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *teacherSrvStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *teacherSrvStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *teacherSrvHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.TeacherSrvHandler.PingPong(ctx, &teacherSrvPingPongStream{stream})
}

type TeacherSrv_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type teacherSrvPingPongStream struct {
	stream server.Stream
}

func (x *teacherSrvPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *teacherSrvPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *teacherSrvPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *teacherSrvPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *teacherSrvPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *teacherSrvPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
