// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/agency-web.proto

package agencyweb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AgencyWeb service

func NewAgencyWebEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AgencyWeb service

type AgencyWebService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (AgencyWeb_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (AgencyWeb_PingPongService, error)
}

type agencyWebService struct {
	c    client.Client
	name string
}

func NewAgencyWebService(name string, c client.Client) AgencyWebService {
	return &agencyWebService{
		c:    c,
		name: name,
	}
}

func (c *agencyWebService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AgencyWeb.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agencyWebService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (AgencyWeb_StreamService, error) {
	req := c.c.NewRequest(c.name, "AgencyWeb.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &agencyWebServiceStream{stream}, nil
}

type AgencyWeb_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type agencyWebServiceStream struct {
	stream client.Stream
}

func (x *agencyWebServiceStream) Close() error {
	return x.stream.Close()
}

func (x *agencyWebServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *agencyWebServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *agencyWebServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *agencyWebServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agencyWebService) PingPong(ctx context.Context, opts ...client.CallOption) (AgencyWeb_PingPongService, error) {
	req := c.c.NewRequest(c.name, "AgencyWeb.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &agencyWebServicePingPong{stream}, nil
}

type AgencyWeb_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type agencyWebServicePingPong struct {
	stream client.Stream
}

func (x *agencyWebServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *agencyWebServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *agencyWebServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *agencyWebServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *agencyWebServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *agencyWebServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for AgencyWeb service

type AgencyWebHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, AgencyWeb_StreamStream) error
	PingPong(context.Context, AgencyWeb_PingPongStream) error
}

func RegisterAgencyWebHandler(s server.Server, hdlr AgencyWebHandler, opts ...server.HandlerOption) error {
	type agencyWeb interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type AgencyWeb struct {
		agencyWeb
	}
	h := &agencyWebHandler{hdlr}
	return s.Handle(s.NewHandler(&AgencyWeb{h}, opts...))
}

type agencyWebHandler struct {
	AgencyWebHandler
}

func (h *agencyWebHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AgencyWebHandler.Call(ctx, in, out)
}

func (h *agencyWebHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AgencyWebHandler.Stream(ctx, m, &agencyWebStreamStream{stream})
}

type AgencyWeb_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type agencyWebStreamStream struct {
	stream server.Stream
}

func (x *agencyWebStreamStream) Close() error {
	return x.stream.Close()
}

func (x *agencyWebStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *agencyWebStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *agencyWebStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *agencyWebStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *agencyWebHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AgencyWebHandler.PingPong(ctx, &agencyWebPingPongStream{stream})
}

type AgencyWeb_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type agencyWebPingPongStream struct {
	stream server.Stream
}

func (x *agencyWebPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *agencyWebPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *agencyWebPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *agencyWebPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *agencyWebPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *agencyWebPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
