// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/security.proto

package security

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Security service

func NewSecurityEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Security service

type SecurityService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Security_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Security_PingPongService, error)
}

type securityService struct {
	c    client.Client
	name string
}

func NewSecurityService(name string, c client.Client) SecurityService {
	return &securityService{
		c:    c,
		name: name,
	}
}

func (c *securityService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Security.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Security_StreamService, error) {
	req := c.c.NewRequest(c.name, "Security.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &securityServiceStream{stream}, nil
}

type Security_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type securityServiceStream struct {
	stream client.Stream
}

func (x *securityServiceStream) Close() error {
	return x.stream.Close()
}

func (x *securityServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *securityServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *securityServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *securityServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *securityService) PingPong(ctx context.Context, opts ...client.CallOption) (Security_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Security.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &securityServicePingPong{stream}, nil
}

type Security_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type securityServicePingPong struct {
	stream client.Stream
}

func (x *securityServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *securityServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *securityServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *securityServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *securityServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *securityServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Security service

type SecurityHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Security_StreamStream) error
	PingPong(context.Context, Security_PingPongStream) error
}

func RegisterSecurityHandler(s server.Server, hdlr SecurityHandler, opts ...server.HandlerOption) error {
	type security interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Security struct {
		security
	}
	h := &securityHandler{hdlr}
	return s.Handle(s.NewHandler(&Security{h}, opts...))
}

type securityHandler struct {
	SecurityHandler
}

func (h *securityHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.SecurityHandler.Call(ctx, in, out)
}

func (h *securityHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SecurityHandler.Stream(ctx, m, &securityStreamStream{stream})
}

type Security_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type securityStreamStream struct {
	stream server.Stream
}

func (x *securityStreamStream) Close() error {
	return x.stream.Close()
}

func (x *securityStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *securityStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *securityStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *securityStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *securityHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.SecurityHandler.PingPong(ctx, &securityPingPongStream{stream})
}

type Security_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type securityPingPongStream struct {
	stream server.Stream
}

func (x *securityPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *securityPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *securityPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *securityPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *securityPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *securityPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
