// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/chat-srv.proto

package chatsrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ChatSrv service

func NewChatSrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ChatSrv service

type ChatSrvService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (ChatSrv_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (ChatSrv_PingPongService, error)
}

type chatSrvService struct {
	c    client.Client
	name string
}

func NewChatSrvService(name string, c client.Client) ChatSrvService {
	return &chatSrvService{
		c:    c,
		name: name,
	}
}

func (c *chatSrvService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ChatSrv.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatSrvService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (ChatSrv_StreamService, error) {
	req := c.c.NewRequest(c.name, "ChatSrv.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &chatSrvServiceStream{stream}, nil
}

type ChatSrv_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type chatSrvServiceStream struct {
	stream client.Stream
}

func (x *chatSrvServiceStream) Close() error {
	return x.stream.Close()
}

func (x *chatSrvServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *chatSrvServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *chatSrvServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *chatSrvServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatSrvService) PingPong(ctx context.Context, opts ...client.CallOption) (ChatSrv_PingPongService, error) {
	req := c.c.NewRequest(c.name, "ChatSrv.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &chatSrvServicePingPong{stream}, nil
}

type ChatSrv_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type chatSrvServicePingPong struct {
	stream client.Stream
}

func (x *chatSrvServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *chatSrvServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *chatSrvServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *chatSrvServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *chatSrvServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *chatSrvServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ChatSrv service

type ChatSrvHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, ChatSrv_StreamStream) error
	PingPong(context.Context, ChatSrv_PingPongStream) error
}

func RegisterChatSrvHandler(s server.Server, hdlr ChatSrvHandler, opts ...server.HandlerOption) error {
	type chatSrv interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type ChatSrv struct {
		chatSrv
	}
	h := &chatSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&ChatSrv{h}, opts...))
}

type chatSrvHandler struct {
	ChatSrvHandler
}

func (h *chatSrvHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ChatSrvHandler.Call(ctx, in, out)
}

func (h *chatSrvHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ChatSrvHandler.Stream(ctx, m, &chatSrvStreamStream{stream})
}

type ChatSrv_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type chatSrvStreamStream struct {
	stream server.Stream
}

func (x *chatSrvStreamStream) Close() error {
	return x.stream.Close()
}

func (x *chatSrvStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *chatSrvStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *chatSrvStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *chatSrvStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *chatSrvHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ChatSrvHandler.PingPong(ctx, &chatSrvPingPongStream{stream})
}

type ChatSrv_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type chatSrvPingPongStream struct {
	stream server.Stream
}

func (x *chatSrvPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *chatSrvPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *chatSrvPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *chatSrvPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *chatSrvPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *chatSrvPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
