// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/agency-srv.proto

package agencysrv

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Class struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassID   string  `protobuf:"bytes,1,opt,name=classID,proto3" json:"classID,omitempty"`
	Price     float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Name      string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Age       string  `protobuf:"bytes,4,opt,name=age,proto3" json:"age,omitempty"`
	StuNumber int32   `protobuf:"varint,5,opt,name=stuNumber,proto3" json:"stuNumber,omitempty"`
	Level     string  `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *Class) Reset() {
	*x = Class{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{0}
}

func (x *Class) GetClassID() string {
	if x != nil {
		return x.ClassID
	}
	return ""
}

func (x *Class) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Class) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Class) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *Class) GetStuNumber() int32 {
	if x != nil {
		return x.StuNumber
	}
	return 0
}

func (x *Class) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type Agency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgencyID      string   `protobuf:"bytes,1,opt,name=agencyID,proto3" json:"agencyID,omitempty"`
	Name          string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tel           string   `protobuf:"bytes,3,opt,name=tel,proto3" json:"tel,omitempty"`
	Rating        float32  `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comments      int32    `protobuf:"varint,5,opt,name=comments,proto3" json:"comments,omitempty"`
	Order         string   `protobuf:"bytes,6,opt,name=order,proto3" json:"order,omitempty"`
	Tags          []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Address       string   `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	AddressDetail string   `protobuf:"bytes,9,opt,name=addressDetail,proto3" json:"addressDetail,omitempty"`
	Distance      float32  `protobuf:"fixed32,10,opt,name=distance,proto3" json:"distance,omitempty"`
	Icon          string   `protobuf:"bytes,11,opt,name=icon,proto3" json:"icon,omitempty"`
	Photos        []string `protobuf:"bytes,12,rep,name=photos,proto3" json:"photos,omitempty"`
	Classes       []*Class `protobuf:"bytes,13,rep,name=classes,proto3" json:"classes,omitempty"`
}

func (x *Agency) Reset() {
	*x = Agency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agency) ProtoMessage() {}

func (x *Agency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agency.ProtoReflect.Descriptor instead.
func (*Agency) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{1}
}

func (x *Agency) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

func (x *Agency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agency) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *Agency) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Agency) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *Agency) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Agency) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Agency) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Agency) GetAddressDetail() string {
	if x != nil {
		return x.AddressDetail
	}
	return ""
}

func (x *Agency) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Agency) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Agency) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Agency) GetClasses() []*Class {
	if x != nil {
		return x.Classes
	}
	return nil
}

type Teacher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeacherID   string   `protobuf:"bytes,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pic         string   `protobuf:"bytes,3,opt,name=pic,proto3" json:"pic,omitempty"`
	Tag         []string `protobuf:"bytes,4,rep,name=tag,proto3" json:"tag,omitempty"`
	Tel         string   `protobuf:"bytes,5,opt,name=tel,proto3" json:"tel,omitempty"`
	Description string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Teacher) Reset() {
	*x = Teacher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Teacher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teacher) ProtoMessage() {}

func (x *Teacher) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teacher.ProtoReflect.Descriptor instead.
func (*Teacher) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{2}
}

func (x *Teacher) GetTeacherID() string {
	if x != nil {
		return x.TeacherID
	}
	return ""
}

func (x *Teacher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Teacher) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *Teacher) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Teacher) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *Teacher) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type OverEvaluation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeneralRate float32 `protobuf:"fixed32,1,opt,name=generalRate,proto3" json:"generalRate,omitempty"`
	UpRate      int32   `protobuf:"varint,2,opt,name=upRate,proto3" json:"upRate,omitempty"`
	GoodRate    float32 `protobuf:"fixed32,3,opt,name=goodRate,proto3" json:"goodRate,omitempty"`
}

func (x *OverEvaluation) Reset() {
	*x = OverEvaluation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OverEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverEvaluation) ProtoMessage() {}

func (x *OverEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverEvaluation.ProtoReflect.Descriptor instead.
func (*OverEvaluation) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{3}
}

func (x *OverEvaluation) GetGeneralRate() float32 {
	if x != nil {
		return x.GeneralRate
	}
	return 0
}

func (x *OverEvaluation) GetUpRate() int32 {
	if x != nil {
		return x.UpRate
	}
	return 0
}

func (x *OverEvaluation) GetGoodRate() float32 {
	if x != nil {
		return x.GoodRate
	}
	return 0
}

type Evaluation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EvaluationID string   `protobuf:"bytes,1,opt,name=evaluationID,proto3" json:"evaluationID,omitempty"`
	Favicon      string   `protobuf:"bytes,2,opt,name=favicon,proto3" json:"favicon,omitempty"` // user's icon
	Rating       float32  `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Username     string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Class        *Class   `protobuf:"bytes,5,opt,name=class,proto3" json:"class,omitempty"`
	Detail       string   `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	Pics         []string `protobuf:"bytes,7,rep,name=pics,proto3" json:"pics,omitempty"`
}

func (x *Evaluation) Reset() {
	*x = Evaluation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Evaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evaluation) ProtoMessage() {}

func (x *Evaluation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evaluation.ProtoReflect.Descriptor instead.
func (*Evaluation) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{4}
}

func (x *Evaluation) GetEvaluationID() string {
	if x != nil {
		return x.EvaluationID
	}
	return ""
}

func (x *Evaluation) GetFavicon() string {
	if x != nil {
		return x.Favicon
	}
	return ""
}

func (x *Evaluation) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Evaluation) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Evaluation) GetClass() *Class {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *Evaluation) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Evaluation) GetPics() []string {
	if x != nil {
		return x.Pics
	}
	return nil
}

type ReadAgencyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgencyID    string   `protobuf:"bytes,1,opt,name=agencyID,proto3" json:"agencyID,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags        []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	FilterItems []string `protobuf:"bytes,4,rep,name=filter_items,json=filterItems,proto3" json:"filter_items,omitempty"`
	S           string   `protobuf:"bytes,5,opt,name=s,proto3" json:"s,omitempty"` // search
}

func (x *ReadAgencyRequest) Reset() {
	*x = ReadAgencyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAgencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAgencyRequest) ProtoMessage() {}

func (x *ReadAgencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAgencyRequest.ProtoReflect.Descriptor instead.
func (*ReadAgencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAgencyRequest) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

func (x *ReadAgencyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadAgencyRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ReadAgencyRequest) GetFilterItems() []string {
	if x != nil {
		return x.FilterItems
	}
	return nil
}

func (x *ReadAgencyRequest) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type ReadAgencyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status          int32     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Agencies        []*Agency `protobuf:"bytes,2,rep,name=agencies,proto3" json:"agencies,omitempty"`
	BrandHistory    string    `protobuf:"bytes,3,opt,name=brandHistory,proto3" json:"brandHistory,omitempty"`
	Characteristics []string  `protobuf:"bytes,4,rep,name=characteristics,proto3" json:"characteristics,omitempty"`
	Msg             string    `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ReadAgencyResponse) Reset() {
	*x = ReadAgencyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAgencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAgencyResponse) ProtoMessage() {}

func (x *ReadAgencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAgencyResponse.ProtoReflect.Descriptor instead.
func (*ReadAgencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{6}
}

func (x *ReadAgencyResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ReadAgencyResponse) GetAgencies() []*Agency {
	if x != nil {
		return x.Agencies
	}
	return nil
}

func (x *ReadAgencyResponse) GetBrandHistory() string {
	if x != nil {
		return x.BrandHistory
	}
	return ""
}

func (x *ReadAgencyResponse) GetCharacteristics() []string {
	if x != nil {
		return x.Characteristics
	}
	return nil
}

func (x *ReadAgencyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AddAgencyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agency          *Agency  `protobuf:"bytes,1,opt,name=agency,proto3" json:"agency,omitempty"`
	BrandHistory    string   `protobuf:"bytes,2,opt,name=brandHistory,proto3" json:"brandHistory,omitempty"`
	Characteristics []string `protobuf:"bytes,3,rep,name=characteristics,proto3" json:"characteristics,omitempty"`
}

func (x *AddAgencyRequest) Reset() {
	*x = AddAgencyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAgencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAgencyRequest) ProtoMessage() {}

func (x *AddAgencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAgencyRequest.ProtoReflect.Descriptor instead.
func (*AddAgencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{7}
}

func (x *AddAgencyRequest) GetAgency() *Agency {
	if x != nil {
		return x.Agency
	}
	return nil
}

func (x *AddAgencyRequest) GetBrandHistory() string {
	if x != nil {
		return x.BrandHistory
	}
	return ""
}

func (x *AddAgencyRequest) GetCharacteristics() []string {
	if x != nil {
		return x.Characteristics
	}
	return nil
}

type AddAgencyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	AgencyID string `protobuf:"bytes,2,opt,name=agencyID,proto3" json:"agencyID,omitempty"`
	Msg      string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AddAgencyResponse) Reset() {
	*x = AddAgencyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAgencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAgencyResponse) ProtoMessage() {}

func (x *AddAgencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAgencyResponse.ProtoReflect.Descriptor instead.
func (*AddAgencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{8}
}

func (x *AddAgencyResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddAgencyResponse) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

func (x *AddAgencyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateAgencyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agency          *Agency    `protobuf:"bytes,1,opt,name=agency,proto3" json:"agency,omitempty"`
	BrandHistory    string     `protobuf:"bytes,2,opt,name=brandHistory,proto3" json:"brandHistory,omitempty"`
	Characteristics []string   `protobuf:"bytes,3,rep,name=characteristics,proto3" json:"characteristics,omitempty"`
	Teachers        []*Teacher `protobuf:"bytes,4,rep,name=teachers,proto3" json:"teachers,omitempty"`
}

func (x *UpdateAgencyRequest) Reset() {
	*x = UpdateAgencyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAgencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgencyRequest) ProtoMessage() {}

func (x *UpdateAgencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgencyRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAgencyRequest) GetAgency() *Agency {
	if x != nil {
		return x.Agency
	}
	return nil
}

func (x *UpdateAgencyRequest) GetBrandHistory() string {
	if x != nil {
		return x.BrandHistory
	}
	return ""
}

func (x *UpdateAgencyRequest) GetCharacteristics() []string {
	if x != nil {
		return x.Characteristics
	}
	return nil
}

func (x *UpdateAgencyRequest) GetTeachers() []*Teacher {
	if x != nil {
		return x.Teachers
	}
	return nil
}

type UpdateAgencyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateAgencyResponse) Reset() {
	*x = UpdateAgencyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAgencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgencyResponse) ProtoMessage() {}

func (x *UpdateAgencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgencyResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAgencyResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateAgencyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteAgencyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgencyID string `protobuf:"bytes,1,opt,name=AgencyID,proto3" json:"AgencyID,omitempty"`
}

func (x *DeleteAgencyRequest) Reset() {
	*x = DeleteAgencyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAgencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgencyRequest) ProtoMessage() {}

func (x *DeleteAgencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgencyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAgencyRequest) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

type DeleteAgencyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteAgencyResponse) Reset() {
	*x = DeleteAgencyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAgencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgencyResponse) ProtoMessage() {}

func (x *DeleteAgencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgencyResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAgencyResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteAgencyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ReadEvaluationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgencyID     string `protobuf:"bytes,1,opt,name=agencyID,proto3" json:"agencyID,omitempty"`
	Uid          string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	EvaluationID string `protobuf:"bytes,3,opt,name=evaluationID,proto3" json:"evaluationID,omitempty"`
}

func (x *ReadEvaluationsRequest) Reset() {
	*x = ReadEvaluationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadEvaluationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEvaluationsRequest) ProtoMessage() {}

func (x *ReadEvaluationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEvaluationsRequest.ProtoReflect.Descriptor instead.
func (*ReadEvaluationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{13}
}

func (x *ReadEvaluationsRequest) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

func (x *ReadEvaluationsRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ReadEvaluationsRequest) GetEvaluationID() string {
	if x != nil {
		return x.EvaluationID
	}
	return ""
}

type ReadEvaluationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Evaluation     []*Evaluation   `protobuf:"bytes,1,rep,name=evaluation,proto3" json:"evaluation,omitempty"`
	OverEvaluation *OverEvaluation `protobuf:"bytes,2,opt,name=overEvaluation,proto3" json:"overEvaluation,omitempty"`
	Msg            string          `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Status         int32           `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ReadEvaluationsResponse) Reset() {
	*x = ReadEvaluationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadEvaluationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEvaluationsResponse) ProtoMessage() {}

func (x *ReadEvaluationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEvaluationsResponse.ProtoReflect.Descriptor instead.
func (*ReadEvaluationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{14}
}

func (x *ReadEvaluationsResponse) GetEvaluation() []*Evaluation {
	if x != nil {
		return x.Evaluation
	}
	return nil
}

func (x *ReadEvaluationsResponse) GetOverEvaluation() *OverEvaluation {
	if x != nil {
		return x.OverEvaluation
	}
	return nil
}

func (x *ReadEvaluationsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReadEvaluationsResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddEvaluationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Evaluation *Evaluation `protobuf:"bytes,1,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	Uid        string      `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	AgencyID   string      `protobuf:"bytes,3,opt,name=agencyID,proto3" json:"agencyID,omitempty"`
}

func (x *AddEvaluationRequest) Reset() {
	*x = AddEvaluationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEvaluationRequest) ProtoMessage() {}

func (x *AddEvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEvaluationRequest.ProtoReflect.Descriptor instead.
func (*AddEvaluationRequest) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{15}
}

func (x *AddEvaluationRequest) GetEvaluation() *Evaluation {
	if x != nil {
		return x.Evaluation
	}
	return nil
}

func (x *AddEvaluationRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AddEvaluationRequest) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

type AddEvaluationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EvaluationID string `protobuf:"bytes,1,opt,name=evaluationID,proto3" json:"evaluationID,omitempty"`
	Msg          string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Status       int32  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddEvaluationResponse) Reset() {
	*x = AddEvaluationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEvaluationResponse) ProtoMessage() {}

func (x *AddEvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEvaluationResponse.ProtoReflect.Descriptor instead.
func (*AddEvaluationResponse) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{16}
}

func (x *AddEvaluationResponse) GetEvaluationID() string {
	if x != nil {
		return x.EvaluationID
	}
	return ""
}

func (x *AddEvaluationResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AddEvaluationResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateEvaluationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Evaluation *Evaluation `protobuf:"bytes,1,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	Uid        string      `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	AgencyID   string      `protobuf:"bytes,3,opt,name=agencyID,proto3" json:"agencyID,omitempty"`
}

func (x *UpdateEvaluationRequest) Reset() {
	*x = UpdateEvaluationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEvaluationRequest) ProtoMessage() {}

func (x *UpdateEvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEvaluationRequest.ProtoReflect.Descriptor instead.
func (*UpdateEvaluationRequest) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateEvaluationRequest) GetEvaluation() *Evaluation {
	if x != nil {
		return x.Evaluation
	}
	return nil
}

func (x *UpdateEvaluationRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UpdateEvaluationRequest) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

type UpdateEvaluationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg    string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Status int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateEvaluationResponse) Reset() {
	*x = UpdateEvaluationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEvaluationResponse) ProtoMessage() {}

func (x *UpdateEvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEvaluationResponse.ProtoReflect.Descriptor instead.
func (*UpdateEvaluationResponse) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateEvaluationResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UpdateEvaluationResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeleteEvaluationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EvaluationID string `protobuf:"bytes,1,opt,name=evaluationID,proto3" json:"evaluationID,omitempty"`
	Uid          string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	AgencyID     string `protobuf:"bytes,3,opt,name=agencyID,proto3" json:"agencyID,omitempty"`
}

func (x *DeleteEvaluationRequest) Reset() {
	*x = DeleteEvaluationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEvaluationRequest) ProtoMessage() {}

func (x *DeleteEvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEvaluationRequest.ProtoReflect.Descriptor instead.
func (*DeleteEvaluationRequest) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteEvaluationRequest) GetEvaluationID() string {
	if x != nil {
		return x.EvaluationID
	}
	return ""
}

func (x *DeleteEvaluationRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DeleteEvaluationRequest) GetAgencyID() string {
	if x != nil {
		return x.AgencyID
	}
	return ""
}

type DeleteEvaluationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg    string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Status int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteEvaluationResponse) Reset() {
	*x = DeleteEvaluationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEvaluationResponse) ProtoMessage() {}

func (x *DeleteEvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEvaluationResponse.ProtoReflect.Descriptor instead.
func (*DeleteEvaluationResponse) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteEvaluationResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DeleteEvaluationResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetNearbyAgenciesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agency *Agency `protobuf:"bytes,1,opt,name=agency,proto3" json:"agency,omitempty"`
}

func (x *GetNearbyAgenciesRequest) Reset() {
	*x = GetNearbyAgenciesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNearbyAgenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyAgenciesRequest) ProtoMessage() {}

func (x *GetNearbyAgenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyAgenciesRequest.ProtoReflect.Descriptor instead.
func (*GetNearbyAgenciesRequest) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{21}
}

func (x *GetNearbyAgenciesRequest) GetAgency() *Agency {
	if x != nil {
		return x.Agency
	}
	return nil
}

type GetNearbyAgenciesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNearbyAgenciesResponse) Reset() {
	*x = GetNearbyAgenciesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agency_srv_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNearbyAgenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyAgenciesResponse) ProtoMessage() {}

func (x *GetNearbyAgenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agency_srv_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyAgenciesResponse.ProtoReflect.Descriptor instead.
func (*GetNearbyAgenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_agency_srv_proto_rawDescGZIP(), []int{22}
}

var File_proto_agency_srv_proto protoreflect.FileDescriptor

var file_proto_agency_srv_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2d, 0x73,
	0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79,
	0x73, 0x72, 0x76, 0x22, 0x91, 0x01, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x75, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xdc, 0x02, 0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e,
	0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x74, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x24, 0x0a, 0x0d,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x18, 0x0c, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x07, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x07, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x66, 0x0a, 0x0e,
	0x4f, 0x76, 0x65, 0x72, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x0a, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x61, 0x74, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x75, 0x70, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64,
	0x52, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64,
	0x52, 0x61, 0x74, 0x65, 0x22, 0xd2, 0x01, 0x0a, 0x0a, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x76, 0x69, 0x63,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x76, 0x69, 0x63, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76,
	0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x63, 0x73, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x63, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x11, 0x52, 0x65,
	0x61, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x01, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x41, 0x67, 0x65,
	0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72,
	0x76, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x8b, 0x01, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79,
	0x73, 0x72, 0x76, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x06, 0x61, 0x67, 0x65, 0x6e,
	0x63, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x22, 0x59, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xbe, 0x01, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e,
	0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x22,
	0x0a, 0x0c, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x2e, 0x0a, 0x08,
	0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x52, 0x08, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x22, 0x40, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x31,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49,
	0x44, 0x22, 0x40, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x6a, 0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x45, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x65,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22,
	0xbd, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x65,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x45, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x0e, 0x6f, 0x76, 0x65, 0x72, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x4f, 0x76, 0x65, 0x72, 0x45, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x6f, 0x76, 0x65, 0x72, 0x45, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x7b, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x65, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x22, 0x65, 0x0a, 0x15,
	0x41, 0x64, 0x64, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x7e, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35,
	0x0a, 0x0a, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x49, 0x44, 0x22, 0x44, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6b, 0x0a, 0x17, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x67,
	0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x67,
	0x65, 0x6e, 0x63, 0x79, 0x49, 0x44, 0x22, 0x44, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x45, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e,
	0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x06, 0x61, 0x67, 0x65,
	0x6e, 0x63, 0x79, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79,
	0x41, 0x67, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0xa1, 0x06, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x72, 0x76, 0x12, 0x52,
	0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x1b, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x64, 0x64, 0x41,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x67, 0x65, 0x6e,
	0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1e, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x51, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x1e, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72,
	0x76, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x73, 0x72, 0x76, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54,
	0x0a, 0x0d, 0x41, 0x64, 0x64, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x64, 0x64, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x41, 0x64, 0x64,
	0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76,
	0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63,
	0x79, 0x73, 0x72, 0x76, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79,
	0x73, 0x72, 0x76, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x76,
	0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x60, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x41,
	0x67, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x23, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79,
	0x73, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x41, 0x67, 0x65,
	0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72,
	0x62, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x61, 0x67,
	0x65, 0x6e, 0x63, 0x79, 0x73, 0x72, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_agency_srv_proto_rawDescOnce sync.Once
	file_proto_agency_srv_proto_rawDescData = file_proto_agency_srv_proto_rawDesc
)

func file_proto_agency_srv_proto_rawDescGZIP() []byte {
	file_proto_agency_srv_proto_rawDescOnce.Do(func() {
		file_proto_agency_srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_agency_srv_proto_rawDescData)
	})
	return file_proto_agency_srv_proto_rawDescData
}

var file_proto_agency_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_agency_srv_proto_goTypes = []interface{}{
	(*Class)(nil),                     // 0: agencysrv.Class
	(*Agency)(nil),                    // 1: agencysrv.Agency
	(*Teacher)(nil),                   // 2: agencysrv.Teacher
	(*OverEvaluation)(nil),            // 3: agencysrv.OverEvaluation
	(*Evaluation)(nil),                // 4: agencysrv.Evaluation
	(*ReadAgencyRequest)(nil),         // 5: agencysrv.ReadAgencyRequest
	(*ReadAgencyResponse)(nil),        // 6: agencysrv.ReadAgencyResponse
	(*AddAgencyRequest)(nil),          // 7: agencysrv.AddAgencyRequest
	(*AddAgencyResponse)(nil),         // 8: agencysrv.AddAgencyResponse
	(*UpdateAgencyRequest)(nil),       // 9: agencysrv.UpdateAgencyRequest
	(*UpdateAgencyResponse)(nil),      // 10: agencysrv.UpdateAgencyResponse
	(*DeleteAgencyRequest)(nil),       // 11: agencysrv.DeleteAgencyRequest
	(*DeleteAgencyResponse)(nil),      // 12: agencysrv.DeleteAgencyResponse
	(*ReadEvaluationsRequest)(nil),    // 13: agencysrv.ReadEvaluationsRequest
	(*ReadEvaluationsResponse)(nil),   // 14: agencysrv.ReadEvaluationsResponse
	(*AddEvaluationRequest)(nil),      // 15: agencysrv.AddEvaluationRequest
	(*AddEvaluationResponse)(nil),     // 16: agencysrv.AddEvaluationResponse
	(*UpdateEvaluationRequest)(nil),   // 17: agencysrv.UpdateEvaluationRequest
	(*UpdateEvaluationResponse)(nil),  // 18: agencysrv.UpdateEvaluationResponse
	(*DeleteEvaluationRequest)(nil),   // 19: agencysrv.DeleteEvaluationRequest
	(*DeleteEvaluationResponse)(nil),  // 20: agencysrv.DeleteEvaluationResponse
	(*GetNearbyAgenciesRequest)(nil),  // 21: agencysrv.GetNearbyAgenciesRequest
	(*GetNearbyAgenciesResponse)(nil), // 22: agencysrv.GetNearbyAgenciesResponse
}
var file_proto_agency_srv_proto_depIdxs = []int32{
	0,  // 0: agencysrv.Agency.classes:type_name -> agencysrv.Class
	0,  // 1: agencysrv.Evaluation.class:type_name -> agencysrv.Class
	1,  // 2: agencysrv.ReadAgencyResponse.agencies:type_name -> agencysrv.Agency
	1,  // 3: agencysrv.AddAgencyRequest.agency:type_name -> agencysrv.Agency
	1,  // 4: agencysrv.UpdateAgencyRequest.agency:type_name -> agencysrv.Agency
	2,  // 5: agencysrv.UpdateAgencyRequest.teachers:type_name -> agencysrv.Teacher
	4,  // 6: agencysrv.ReadEvaluationsResponse.evaluation:type_name -> agencysrv.Evaluation
	3,  // 7: agencysrv.ReadEvaluationsResponse.overEvaluation:type_name -> agencysrv.OverEvaluation
	4,  // 8: agencysrv.AddEvaluationRequest.evaluation:type_name -> agencysrv.Evaluation
	4,  // 9: agencysrv.UpdateEvaluationRequest.evaluation:type_name -> agencysrv.Evaluation
	1,  // 10: agencysrv.GetNearbyAgenciesRequest.agency:type_name -> agencysrv.Agency
	5,  // 11: agencysrv.AgencySrv.ReadAgencyDetails:input_type -> agencysrv.ReadAgencyRequest
	7,  // 12: agencysrv.AgencySrv.AddAgency:input_type -> agencysrv.AddAgencyRequest
	9,  // 13: agencysrv.AgencySrv.UpdateAgency:input_type -> agencysrv.UpdateAgencyRequest
	11, // 14: agencysrv.AgencySrv.DeleteAgency:input_type -> agencysrv.DeleteAgencyRequest
	13, // 15: agencysrv.AgencySrv.ReadEvaluations:input_type -> agencysrv.ReadEvaluationsRequest
	15, // 16: agencysrv.AgencySrv.AddEvaluation:input_type -> agencysrv.AddEvaluationRequest
	17, // 17: agencysrv.AgencySrv.UpdateEvaluation:input_type -> agencysrv.UpdateEvaluationRequest
	19, // 18: agencysrv.AgencySrv.DeleteEvaluation:input_type -> agencysrv.DeleteEvaluationRequest
	21, // 19: agencysrv.AgencySrv.GetNearbyAgencies:input_type -> agencysrv.GetNearbyAgenciesRequest
	6,  // 20: agencysrv.AgencySrv.ReadAgencyDetails:output_type -> agencysrv.ReadAgencyResponse
	8,  // 21: agencysrv.AgencySrv.AddAgency:output_type -> agencysrv.AddAgencyResponse
	10, // 22: agencysrv.AgencySrv.UpdateAgency:output_type -> agencysrv.UpdateAgencyResponse
	12, // 23: agencysrv.AgencySrv.DeleteAgency:output_type -> agencysrv.DeleteAgencyResponse
	14, // 24: agencysrv.AgencySrv.ReadEvaluations:output_type -> agencysrv.ReadEvaluationsResponse
	16, // 25: agencysrv.AgencySrv.AddEvaluation:output_type -> agencysrv.AddEvaluationResponse
	18, // 26: agencysrv.AgencySrv.UpdateEvaluation:output_type -> agencysrv.UpdateEvaluationResponse
	20, // 27: agencysrv.AgencySrv.DeleteEvaluation:output_type -> agencysrv.DeleteEvaluationResponse
	22, // 28: agencysrv.AgencySrv.GetNearbyAgencies:output_type -> agencysrv.GetNearbyAgenciesResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_agency_srv_proto_init() }
func file_proto_agency_srv_proto_init() {
	if File_proto_agency_srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_agency_srv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Class); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Agency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Teacher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OverEvaluation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Evaluation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAgencyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAgencyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAgencyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAgencyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAgencyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAgencyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAgencyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAgencyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadEvaluationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadEvaluationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEvaluationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEvaluationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEvaluationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEvaluationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEvaluationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEvaluationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNearbyAgenciesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agency_srv_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNearbyAgenciesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_agency_srv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agency_srv_proto_goTypes,
		DependencyIndexes: file_proto_agency_srv_proto_depIdxs,
		MessageInfos:      file_proto_agency_srv_proto_msgTypes,
	}.Build()
	File_proto_agency_srv_proto = out.File
	file_proto_agency_srv_proto_rawDesc = nil
	file_proto_agency_srv_proto_goTypes = nil
	file_proto_agency_srv_proto_depIdxs = nil
}
