// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/agency-srv.proto

package agencysrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AgencySrv service

func NewAgencySrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AgencySrv service

type AgencySrvService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (AgencySrv_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (AgencySrv_PingPongService, error)
}

type agencySrvService struct {
	c    client.Client
	name string
}

func NewAgencySrvService(name string, c client.Client) AgencySrvService {
	return &agencySrvService{
		c:    c,
		name: name,
	}
}

func (c *agencySrvService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AgencySrv.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agencySrvService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (AgencySrv_StreamService, error) {
	req := c.c.NewRequest(c.name, "AgencySrv.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &agencySrvServiceStream{stream}, nil
}

type AgencySrv_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type agencySrvServiceStream struct {
	stream client.Stream
}

func (x *agencySrvServiceStream) Close() error {
	return x.stream.Close()
}

func (x *agencySrvServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *agencySrvServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *agencySrvServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *agencySrvServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agencySrvService) PingPong(ctx context.Context, opts ...client.CallOption) (AgencySrv_PingPongService, error) {
	req := c.c.NewRequest(c.name, "AgencySrv.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &agencySrvServicePingPong{stream}, nil
}

type AgencySrv_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type agencySrvServicePingPong struct {
	stream client.Stream
}

func (x *agencySrvServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *agencySrvServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *agencySrvServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *agencySrvServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *agencySrvServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *agencySrvServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for AgencySrv service

type AgencySrvHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, AgencySrv_StreamStream) error
	PingPong(context.Context, AgencySrv_PingPongStream) error
}

func RegisterAgencySrvHandler(s server.Server, hdlr AgencySrvHandler, opts ...server.HandlerOption) error {
	type agencySrv interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type AgencySrv struct {
		agencySrv
	}
	h := &agencySrvHandler{hdlr}
	return s.Handle(s.NewHandler(&AgencySrv{h}, opts...))
}

type agencySrvHandler struct {
	AgencySrvHandler
}

func (h *agencySrvHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AgencySrvHandler.Call(ctx, in, out)
}

func (h *agencySrvHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AgencySrvHandler.Stream(ctx, m, &agencySrvStreamStream{stream})
}

type AgencySrv_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type agencySrvStreamStream struct {
	stream server.Stream
}

func (x *agencySrvStreamStream) Close() error {
	return x.stream.Close()
}

func (x *agencySrvStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *agencySrvStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *agencySrvStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *agencySrvStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *agencySrvHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AgencySrvHandler.PingPong(ctx, &agencySrvPingPongStream{stream})
}

type AgencySrv_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type agencySrvPingPongStream struct {
	stream server.Stream
}

func (x *agencySrvPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *agencySrvPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *agencySrvPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *agencySrvPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *agencySrvPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *agencySrvPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
